name: Devel

on: 
    workflow_dispatch:
    schedule:
    # Run the job once a week
    - cron: '0 0 * * 0'
    
jobs:
  build:
    name: build devel and master images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker-deployment-images
        uses: actions/checkout@v2
        
      - name: Repository Dispatch for building images
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: MSECode/docker-deployment-images-testing
          event-type: cron_trigger
          client-payload: '{"version": "master", "type": "cron_trigger", "img_list": "superbuild"}'
